export const SLASH = "/"
export const USER_REGISTER = "/registro-de-usuario"
export const MY_APPOINTMENTS = "/mis-turnos"
export const  ABOUT   =  "/quienes-somos"
export const LOGIN = "/iniciar-sesión"