export const SLASH = "/"
export const USER_REGISTER = "/registro-de-usuario"
export const MY_APPOINTMENTS = "/mis-turnos"
export const LOGIN = "/iniciar-sesión"
export const  ABOUT_US   =  "/quienes-somos"
export const CONTACT = "/contacto"